### PR TITLE
feat: Update designs for Staking/Unstaking

### LINKED ISSUE #263: Update design for staking to a collator
As a portal user, i should see new design for staking flow

## Acceptance criteria
* on `/staking`
* On the figma file all the screens under title "Stake flow" should be implemented

## Notes
* This ticket if for both versions
* This is only for desktop

## Wireframe
https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=2849-5156&mode=design&t=75cQjduNPnz4bezE-4

### LINKED ISSUE #264: Update design for unstaking from a collator
As a portal user, i should see new design for unstaking flow

## Acceptance criteria
* on `/staking`
* On the figma file all the screens under title "Unstake flow" should be implemented

## Notes
* This ticket if for both versions

## Wireframe
https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=395-6035&mode=design&t=t1rNti6sG2YwCnwQ-4

### LINKED ISSUE #266: Update design for updating staking rewards

### PR DESCRIPTION
**Pull request by gonzamontiel**
- [x] Update colors & fonts
- [x] Created Amount component (similar to From), without the asset selector
- [x]  Update general designs for staking/unstaking flow
- [x] Update specific designs for Staking
- [x] Update specific designs for Rewards
- [x] Update specific designs for Unstaking

Closes #263 
Closes #264 
Closes #266

### CODE REVIEW

**Review by ebma — APPROVED** [review]
It looks good to me overall, at least it's implemented as in the designs.

Two things:
- I think showing the 'fee' is now super useless because it will always be so low that it will get truncated to 0.00. We should maybe instead show something like 0.1 microPEN or similar
- The 'Balance' vs 'Available Balance' is confusing to me. As a user I don't necessarily understand what's what.
image

Since it's okay overall, I approve. @prayagd please also have a look at the deploy preview to check if it works how you expected.

**Review by prayagd — APPROVED** [review]
Looks good on my end too

**Comment by gonzamontiel** [comment]
> It looks good to me overall, at least it's implemented as in the designs.
> 
> Two things:
> 
> * I think showing the 'fee' is now super useless because it will always be so low that it will get truncated to 0.00. We should maybe instead show something like 0.1 microPEN or similar
> * The 'Balance' vs 'Available Balance' is confusing to me. As a user I don't necessarily understand what's what.
> 
Thank you for the comments, I changed the dialog so now it shows the number formatted (like you suggested) and change the wording a little bit.

**Pull request merged**
