### PR TITLE
Add fund wallet option to the portal

### LINKED ISSUE #421: Add fund wallet option to the Portal
## Context
Currently all the PEN and AMPE buying and exchanging options are not clubbed and not very clear to the end user in attempt to fix that, this ticket aims at clubbing them under the "Fund wallet" feature where the user would get option to buy or exchange PEN and AMPE tokens

As a portal user, i should be able to buy or exchange PEN and AMPE using the Fund wallet option

## Acceptance criteria
* Remove "Zenlink AMM" option from Pendulum and Amplitude menu
* Remove "Buy PEN" option from Pendulum menu
* Show "Fund wallet" option in the side menu for both Pendulum and Amplitude with the icon given in the design, this feature should be available on the /fund url
* on clicking the option show on the screen two options "Buy" and "Exchange"
* Under "Buy"
    * For Pendulum show Alchemy Pay
    * For Amplitude show nothing
* Under "Exchange"
    * For Pendulum show Zenlink, Stellaswap and MEXC
    * For Amplitude show Zenlink
* Clicking on any of the above options should redirect to the respective onramps or exchanges, links are provided in the note section below
* User should be able to switch between Buy and Exchange fields
* Show redirect icons on each item under "Buy" and "Exchange"
* Please follow the same text provided in the design for Pendulum, text for "Buy" section Amplitude is "Currently no options available, Try Exchange!"

## Design
Pendulum - https://www.figma.com/proto/5up5sghcttBogehUq4255i/App?node-id=4054-757&t=BaiSFdnImuUIHPSI-0&scaling=min-zoom&content-scaling=fixed&page-id=3979%3A1234&starting-point-node-id=4054%3A757&show-proto-sidebar=1
Amplitude - https://www.figma.com/proto/5up5sghcttBogehUq4255i/App?node-id=4053-522&t=BaiSFdnImuUIHPSI-0&scaling=min-zoom&content-scaling=fixed&page-id=3979%3A1234&starting-point-node-id=4053%3A522&show-proto-sidebar=1

### Note
* Zenlink - https://app.zenlink.pro/swap
* Stellaswap - https://app.stellaswap.com/exchange/swap
* MEXC - https://www.mexc.com/exchange/PEN_USDT
* Alchemy Pay - Redirect link for Alchemy Pay

### LINKED ISSUE #540: Add Banxa onramp for PEN to the Portal menu
## Context
This is the placeholder ticket until all details are received from the Banxa team

### PR DESCRIPTION
**Pull request by ebma**
This PR adds a new page 'Fund wallet', hidden on Foucoco. 

Note: The design of the tab backgrounds for Pendulum [here](https://www.figma.com/proto/5up5sghcttBogehUq4255i/Pendulum-Design?node-id=4054-757&t=BaiSFdnImuUIHPSI-0&scaling=min-zoom&content-scaling=fixed&page-id=3979%3A1234&starting-point-node-id=4054%3A757) is not accurate IMO, so I made it reflect the colors of the theme. 

Closes #421 and closes #540.

### CODE REVIEW

**Comment by Sharqiewicz** [comment]
@ebma @prayagd Maybe for Foucoco - Fund Wallet - should redirect to the faucet?

**Comment by Sharqiewicz** [comment]
@ebma I changed the ExternalIcon to be a .svg file instead of react component for optimisation

**Comment by ebma** [comment]
> Maybe for Foucoco - Fund Wallet - should redirect to the faucet?

Makes sense 👍  objections @prayagd?

**Review by prayagd — CHANGES_REQUESTED** [review]
Screenshot 2024-10-22 at 11 31 29 AM

- Zenlink is not visible on Amplitude can we please add a different logo, let me ask the zenlink team for the right one
- Can we add one more option under Pendulum buy for Banxa? https://checkout.banxa.com/, there is ticket for it but maybe we can sneak that into this #540 
- Apart from this all the links work correctly all tested
- yes, i agree to redirecting to Faucet on foucoco

**Comment by Sharqiewicz** [comment]
@prayagd I already fixed the Zenlink on Amplitude, please check

**Comment by ebma** [comment]
@Sharqiewicz are you going to add the faucet item for Foucoco or should I?

**Comment by Sharqiewicz** [comment]
@ebma I'll do it

**Comment by ebma** [comment]
@Sharqiewicz why do you prefer the basic svg files over the components? I doubt that it really makes a large difference in performance but now you had to duplicate the zenlink svg icons whereas the component-based solution would have allowed you to just define the color on the component? It's not a big deal, I'm just curious. 

Besides that, let's maybe change the button color of the 'Faucet' button to something else (secondary?) and change the text to 'Top up with Faucet'. Ideally we'd also only show that button in the 'Buy' case. 

Rest looks good to me and the refactorings are great overall 👍

**Comment by Sharqiewicz** [comment]
@ebma We can’t set a single color for the Zenlink image since it uses both white and pink, not just white. So, I decided to go with the `` and .svg file. When using .svg and not inline svg allows the image to be cached and reduces the bundle size.

Great ideas, I added the changes you mentioned ✅

**Comment by ebma** [comment]
Hmm now the button looks like it's hovered/selected all the time 😅 Sorry for the overhead with this. If we don't show it in conjunction with the 'Buy'/'Exchange' tabs (which I think is good that we don't) let's change the color back to primary. 

image


> We can’t set a single color for the Zenlink image since it uses both white and pink, not just white.

Right but I think in my version, this was already working properly as the color was only passed to the text part and not the little dot IIRC. Doesn't matter too much, I was just curious about your reasoning. Because we could consider replacing all the image components with just the image. But maybe it's better to do this on a case-by-case basis.

**Comment by ebma** [comment]
@prayagd can you please have another look? Your comments should be addressed now.

**Comment by Sharqiewicz** [comment]
@ebma I think when we need the control over styling/animating the SVG then we should use inline svg. If there is no need for styling the SVG using  is more efficient way - reduced bundle size ( our bundle size is big right now, we receive warnings when compiling ), enables browser caching

**Comment by Sharqiewicz** [comment]
@ebma Thanks for changing the button color

**Comment by Sharqiewicz** [comment]
@ebma Do we merge it? Everything is completed ✅

**Pull request merged**
