### PR TITLE
Replace the spacewalk menu item with animation

### PR DESCRIPTION
**Pull request by Sharqiewicz**
### What:

Replace the spacewalk menu item with animation

### How:

✅ implement handling Lottie JSON
✅ implement Spacewalk Lottie animation in Nav

Closes: #362

### CODE REVIEW

**Comment by ebma** [comment]
Why is this still a draft?

**Comment by Sharqiewicz** [comment]
> Why is this still a draft?

The design has to be approved

**Comment by ebma** [comment]
By who? Are those people aware that they are blocking this or should we ping them?

**Comment by Sharqiewicz** [comment]
@ebma It's approved by Klaus. It's ready for review

**Review by ebma — COMMENTED** [review]
Very nice, great job @Sharqiewicz!

Just one thing: Maybe it's just me but I think the 'Spacewalk' text has a slightly darker shade than the other menu items and it would be nice to make them all have the same color or boldness.
image

**Comment by prayagd** [comment]
> Just one thing: Maybe it's just me but I think the 'Spacewalk' text has a slightly darker shade than the other menu items and it would be nice to make them all have the same color or boldness.

@ebma thats expected we are changing the font and color of the menu, the same would be changed for other menu items too, correct me if wrong @Sharqiewicz

**Comment by Sharqiewicz** [comment]
> Very nice, great job @Sharqiewicz!
> 
> Just one thing: Maybe it's just me but I think the 'Spacewalk' text has a slightly darker shade than the other menu items and it would be nice to make them all have the same color or boldness. image

Nice catch! ✅ 
The new color palette will be defined in the GET PEN PR

**Pull request merged**
