### PR TITLE
fix: Make Staking Reward boxes responsive

### LINKED ISSUE #319: Remove side scroll on mobile for staking screen
### Describe the bug

when `/staking` is accessed on mobile, the "Update" and "Claim" buttons are hidden and the user has to side scroll to click on these buttons

### Reproduction

1. Go to '/staking'
2. Scroll sideways to see "Update" and "Claim" buttons

### Expected behavior

The side scroll show be removed and the buttons should be visible directly. 

### Screenshots
image
image

### PR DESCRIPTION
**Pull request by gonzamontiel**
Make staking boxes in _/staking_ react responsively:
Closes #319 

**Up to 640px**
 

Screenshot from 2023-12-20 16 33 54

**Less than 640px**
Screenshot from 2023-12-20 16 31 56

### CODE REVIEW

**Review by prayagd — COMMENTED** [review]
Looks good, just one small thing. The update reward loader looks broken. See screenshot
image

**Review by prayagd — COMMENTED** [review]
Screenshot 2024-02-09 at 12 33 56 PM

@gonzamontiel i still see have to side scroll for the two buttons, i checked in both chrome and brave similar behaviour

**Comment by gonzamontiel** [comment]
> Screenshot 2024-02-09 at 12 33 56 PM
> @gonzamontiel i still see have to side scroll for the two buttons, i checked in both chrome and brave similar behaviour

I don't think the portal can be actually viewed at 380px. I'll fix this case in the PR, but I mean, did you see the table ? I'm not that worried about the buttons (and you can always zoom out a bit).

**Comment by gonzamontiel** [comment]
I reduced margins, now you should be able to click the buttons at small iphone widths. I couldn't get rid of the horizontal scroll, but I don't think is crucial. 
 
Screenshot from 2024-02-09 19 00 20

**Review by prayagd — APPROVED** [review]
Looks good to me now, we can merge

**Pull request merged**
