### PR TITLE
chore: implement prioritize XLM Asset

### PR DESCRIPTION
**Pull request by Sharqiewicz**
### What:

XLM top of the list in the Spacewalk asset dropdown

### How:

✅ Implement prioritizeXLMAsset function
✅ Use prioritizeXLMAsset for assets in "To Pendulum/Amplitude" and "Back To Stellar"

### CODE REVIEW

**Comment by prayagd** [comment]
LGTM, Go from my side

**Comment by annatekl** [comment]
reviewed @Sharqiewicz

**Review by annatekl — COMMENTED** [review]
correct

**Review by prayagd — APPROVED** [review]
LGTM, Lets merge

**Pull request merged**
