### PR TITLE
show Nabla Swap tooltips, change column names

### PR DESCRIPTION
**Pull request by Sharqiewicz**
🦈 PR
---
- [x] Rename the first column of the swap UI to "Asset"
- [x] Add a tool tip next to "Pool liabilities" and "Reserves" titles
- [x] Tool tip message for Pool liabilities - Amount of liquidity provided initially by LPs
- [x] Tool tip message for Reserves - Amount of tokens in the pool

### CODE REVIEW

**Comment by TorstenStueber** [comment]
Sorry @Sharqiewicz this ticket was not ready for dev and should not have been in the Ready column. There is still ongoing discussion.

@prayagd The definition of Pool liabilities as "Amount of liquidity provided initially by LPs" is wrong (see also my comment [here](https://github.com/pendulum-chain/portal/issues/474#issuecomment-2283321794)).

Pool liabilities deviate from the "Amount of liquidity provided initially by LPs" further and further due to
* slippage
* accumulated fees

Eventually the liability will deviate a lot from the "Amount of liquidity provided initially by LPs".

There is no simple, intuitive way to explain what "liability" means. As I wrote before, it is a number used for internal accounting to determine the current slippage.

**Comment by vadaynujra** [comment]
@prayagd not sure if you saw my comment here, but shall we keep the column names consistent in adding the word `Pool`, or not? Let's remove it from both (like Nabla have) as the user is already in the Swap Pools page?

**Comment by prayagd** [comment]
> @prayagd not sure if you saw my comment https://github.com/pendulum-chain/portal/issues/474#issuecomment-2383612899, but shall we keep the column names consistent in adding the word Pool, or not? Let's remove it from both (like Nabla have) as the user is already in the Swap Pools page?

Agree to the suggestion

**Comment by Sharqiewicz** [comment]
@vadaynujra @prayagd What is the conclusion?

**Comment by prayagd** [comment]
@Sharqiewicz I would suggest getting rid of the tool tips and just renaming the first column to "Asset", Suggesting this because the ticket has been going on for a longer time and all further changes can be done in a separate ticket. do you agree @TorstenStueber @ebma ?

**Comment by ebma** [comment]
Sure, we can reduce the scope here and follow up in another ticket.

**Comment by TorstenStueber** [comment]
Yes, agree. Let's get this ticket done with a reduced scope and let's open another ticket if we consider this necessary. I am currently writing the Forex AMM docs in a way that it should work well with the current table layout.

**Comment by prayagd** [comment]
@Sharqiewicz let's reduce the scope and just rename the first column to "Asset"

**Comment by Sharqiewicz** [comment]
@prayagd Is it good now?

**Review by ebma — APPROVED** [review]
Looks good to me. 

This PR also addresses https://github.com/pendulum-chain/portal/issues/592 now so we can close that ticket as well afterwards.

**Review by TorstenStueber — APPROVED** [review]

**Pull request merged**
