### PR TITLE
feat: pagination #62

### PR DESCRIPTION
**Pull request by nejcm**
@gonzamontiel Let me know if this satisfies your needs or is there something more needed. It is as designed on the screenshot. This is only a reusable component so it can be included anywhere not just tables.
It can also be extend to support actual page numbers or even a page selector.

### CODE REVIEW

**Comment by gonzamontiel** [comment]
So this component is necessary indeed, thanks for that. But what I had in mind for #62 was something like `PaginatedTable`, that includes the pagination section _and_ the behavior to load the rows when clicking on the chevron icons. 
So, I can approve this PR as a previous step, but #62 would still be open.

**Review by gonzamontiel — APPROVED** [review]
As I stated in my comment, a good previous step. lgtm!

**Comment by nejcm** [comment]
> So this component is necessary indeed, thanks for that. But what I had in mind for #62 was something like `PaginatedTable`, that includes the pagination section _and_ the behavior to load the rows when clicking on the chevron icons. So, I can approve this PR as a previous step, but #62 would still be open.

I see. Will make a new PR with that today.

**Comment by nejcm** [comment]
@gonzamontiel I updated this PR with the reusable table but it uses the react-table library to display it. You can check [here](https://github.com/pendulum-chain/portal/pull/65/files#diff-193ebe625f046c7606d7806db8425ebf852aefed98ea91762459f5259fa70132) how to  define columns for it which is the only required part for using it.

**Comment by nejcm** [comment]
@gonzamontiel Not sure what is your merge policy but will let you merge this in once you think its ok

**Review by gonzamontiel — APPROVED** [review]
It also comes with a global search? nicee. Looks good to me!

**Comment by gonzamontiel** [comment]
Oh, I see it has some conflicts, feel free to merge it when they are solved @nejcm :)

**Comment by nejcm** [comment]
@gonzamontiel Solve the merge issues. I dont have the perms to merge though

**Pull request merged**
