### PR TITLE
Un-hardcode Type column

### PR DESCRIPTION
**Pull request by gonzamontiel**
- Show 'To <chain_name>' instead of 'To Pendulum' in Transfers Type col

### CODE REVIEW

**Comment by gonzamontiel** [comment]
fyi this will only be visible on Amplitude when #138 is merged

**Comment by prayagd** [comment]
@gonzamontiel I am not able to see the Amplitude list of transfers. So no way to find out whether the type is changed or not.

**Comment by gonzamontiel** [comment]
> @gonzamontiel I am not able to see the Amplitude list of transfers. So no way to find out whether the type is changed or not.

Regarding that:
> fyi this will only be visible on Amplitude when https://github.com/pendulum-chain/portal/pull/138 is merged

Now, I merged staging to this branch, so you can test it.

**Review by prayagd — APPROVED** [review]
yes, i can see the "to Amplitude" type now.

**Pull request merged**
