### PR TITLE
73 update menu items with coming soon

### PR DESCRIPTION
**Pull request by gonzamontiel**
- Add coming soon tag
- Infere colors for Amplitude (designs missing)
- Side change: fixed OpenWallet colors to support both themes

### CODE REVIEW

**Review by ebma — COMMENTED** [review]
Seems like this broke the design of the [collator list](https://deploy-preview-101--rococo-souffle-a625f5.netlify.app/foucoco/collators) on Foucoco/Amplitude?

**Comment by gonzamontiel** [comment]
> Seems like this broke the design of the [collator list](https://deploy-preview-101--rococo-souffle-a625f5.netlify.app/foucoco/collators) on Foucoco/Amplitude?

Nope, unfortunately this is staging. I am side-fixing it in https://github.com/pendulum-chain/portal/pull/91

**Review by ebma — COMMENTED** [review]
Ah okay. If that issue is on staging already we can merge this one.

**Review by ebma — APPROVED** [review]

**Comment by prayagd** [comment]
moving this to development

**Pull request merged**
