### PR TITLE
Chore/update packages (Ready)

### PR DESCRIPTION
**Pull request by Sharqiewicz**
🦈 The goal of the PR is to update all the outdated packages. Some of them are even 18 months old.

👷 Removed packages
- [x] stellar-sdk/stellar-base (deprecated) => installed @stellar/stellar-sdk
- [x] sass => we had only 1 file using sass, I changed it plain css and removed sass 
- [x] semantic-relase (CHANGELOD.md + release.config.js)
- [x] @testing-library/react-hooks (not used)

To investigate:
- If we need `luxon` package. We use it only once.
- If we need Babel for JEST. Our transpiler is `esbuild`, we don't need Babel for transpilation. Our testing enviroment was configured long time ago to use Babel. I think we should consider changing it to remove Babel from our repo. (it creates confusion) - create a task
- Move from `react-lottie` to `react-lottie-player` ( `react-lottie-player` doesn't use eval )

I did not
- investigate graphql dependencies
- migrate from preact to react

Changed the minimum version of yarn to be `>=4.0.0`

- [x] Fixed package manager warnings. The rest of the warnings will be resolved once we migrate from Preact to React.

Note: Recent DaisyUI generates css-syntax-error on build. Can be ignored.

### CODE REVIEW

**Comment by Sharqiewicz** [comment]
@ebma Ready for review

**Comment by Sharqiewicz** [comment]
@ebma 

I created tasks:
- remove `luxon`: https://github.com/pendulum-chain/portal/issues/601
- remove `babel`: https://github.com/pendulum-chain/portal/issues/602

‘eval’ is a pass-through for XSS attacks, the best practice is to eliminate it from the application altogether.

**Comment by ebma** [comment]
Cool 👍 how about you tackle those issues in about a month when the monthly reminder fires again?

**Comment by Sharqiewicz** [comment]
@ebma I think we can ignore the warning. We won't use any TS features from versions greater than 5.5.0

**Comment by Sharqiewicz** [comment]
created task: https://github.com/pendulum-chain/portal/issues/603

**Comment by Sharqiewicz** [comment]
@ebma I think it's ready

**Comment by ebma** [comment]
Nice, let's go 🚀

**Comment by Sharqiewicz** [comment]
@prayagd @arjun There are no new features in this update. I have updated nearly all of the key packages we use for development. We just need to verify that everything works correctly and ensure there are no regressions.

**Comment by prayagd** [comment]
> We just need to verify that everything works correctly and ensure there are no regressions.

Dumb question: How do i check if there are no regressions?

**Comment by Sharqiewicz** [comment]
@prayagd I think in order to test if there is no regression, we have to ensure that **every** Portal feature is working correctly. So we should test staking, forex amm and spacewalk

**Comment by prayagd** [comment]
Will do

**Review by prayagd — APPROVED** [review]
- Staking, unstaking and claim worked
- Swap, adding liquidity to swap pool and bsp worked
- Issue and Redeem works
LGTM

**Comment by ebma** [comment]
>  I think in order to test if there is no regression, we have to ensure that every Portal feature is working correctly. So we should test staking, forex amm and spacewalk.

Yes exactly, that's what I meant. Thanks @Sharqiewicz for pointing it out and @prayagd for testing.

**Pull request merged**
