### PR TITLE
Improve Reimbursed Dialog box

### LINKED ISSUE #103: Show reimbursed value in KSM.
As a spacewalk user, i should be able to see the amount of KSM that was reimbursed by burning the bridged asset

# Acceptance criteria
* If redeem request failed and user chooses to reimburse
* Show the KSM equivalent of bridged asset that was burned. 
* Currently the value in displayed in bridged asset. 
Screenshot 2023-04-20 at 2 57 02 PM

### LINKED ISSUE #104: Add "Inconvenience Compensation"  in the reimburse dialog box.
As a spacewalk user, i should be able to see the compensation provided for failed redeem request when reimbursed

# Acceptance criteria
* Show "Inconvenience Compensation" under bridge fee in the reimburse dialog box
* Show this amount in KSM/DOT(collateral asset)

### PR DESCRIPTION
**Pull request by gonzamontiel**
- Added 'Success' style to Reimbursed transfers (green)
- Added oracle pallet hook (WIP)
- Closes #103 
- Closes #104 

Still a draft because I need to fetch currency_to_usd() and usd_to_currency() from oracle pallet, and they are not yet accessible through RPC.

### CODE REVIEW

**Comment by gonzamontiel** [comment]
I've updated the code to use the oracle pallet, while the types are correct now, we need to wait that the nodes are redeployed to be able to test it. I mark it ready but please don't review it yet.

**Comment by gonzamontiel** [comment]
I am blocked in this one by an error that I couldn't solve today. The error appears trying to call
`api.rpc.oracle.currencyToUsd(amount, currency)`. I am not able to build an amount that the functions is happey about.
I tried passing a number, a BN, building a BalanceWrapper {amount: Balance}, a string, etc. And everytime a similar error appears, which I attach. When, instead of an integer, I pass a string representing the number, the exact same error appears.

Screenshot from 2023-06-08 14 53 42

**Comment by gonzamontiel** [comment]
> @gonzamontiel did you manage to fix the issue you described [above](https://github.com/pendulum-chain/portal/pull/185#issuecomment-1583099314)? I still see the same error messages.

Well now that you say it, I didn't get that error, but now I get:
```
TypeError: Cannot read properties of undefined (reading 'currencyToUsd')
    at getExchangeRate (oracle.tsx:26:55)
    at Object.__ (TransferDialog.tsx:238:5)
    at w (index.js:492:18)
    at Array.forEach (<anonymous>)
    at b (index.js:419:38)
```
which is weird because the types are updated.

**Comment by gonzamontiel** [comment]
> But you are testing on Foucoco right? Or did you select another network?

Indeed, testing in Foucoco.

**Comment by ebma** [comment]
But when I use the deploy preview page, and navigate to a 'reimbursed' redeem request in the transfers page, I see the following error. Is it different for you?
image

**Pull request closed without merging**
